---
title: "Charlie Bruce"
output:
  html_document:
    output_dir: docs
    toc: FALSE
    includes:
      in_header: GA_Script.html
---

#
#
#
#
#
# About
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


My name is Charlie Bruce. I will be graduating with my Master's in Public Policy in May 2023 from the [Frank Batten School of Leadership and Public Policy](https://batten.virginia.edu/) at UVA.

I began my journey with statistical models while working as a political organizer, where I built voter universes for Democratic campaigns. To determine which voters to contact, we used a propensity scoring system that ranked voters based on their likelihood to vote Democratic and their voting frequency.

To make a lasting impact and gain leadership skills, I applied to graduate school in public policy, where I learned the adaptive leadership method à la Ron Heifetz. This past summer, I had the opportunity to intern at the Department of Justice, where I worked on building data visualizations in R for various projects.

For life's next chapter, I am applying to positions that bring together policy analysis and data visualization. You can reach me via email at [ceb8dv@virginia.edu](mailto:ceb8dv@virginia.edu).  

#
#
#


